### ISSUE TITLE
Diminishing returns

### ISSUE THREAD

**Issue by eXeLe** [favll/pogom#156]
Is there any way to mitigate diminishing returns?
I was scanning my whole sity (18000 radius) in ~3hr30min with 70 accounts.
Now I run 1066 account and full scan cycle is ~1hr.
It sounds pretty bad - x15 more accounts and x3.5 scan speed.

I'm running on SSD, 16Gb RAM and good CPU.
Any ideas? May be moving to MySQL or MSSQL if RDBMS is a problem? Or some caching/raw data writes?

**Comment by nborrmann** [comment]
Moving to a different db might help, yes.

If you know python and could test this, I would welcome your results. Or if you could post any profile logs (using `cProfile`).

**Comment by drewreece** [comment]
1066 accounts!?
Why do you need to scan an entire city?

You realise how many requests you are making - have you looked a how much data you are sending & receiving? 

I dare say your diminishing returns might be because your accounts are slowly being banned. Have you look at the logs or the command output? Are the servers actually returning results? Changing the DB will not alter anything if Niantic are simply telling you nothing exists or blocking/ banning your accounts or IP.

There are other tools if you just want to get spawn locations, using PokémonGo-Map is very request heavy.

**Comment by eXeLe** [comment]
cProfile output
http://pastebin.com/CFvJbGwU
I'm not sure if thats what you want, Just stopped script after ~1hr running.

Not sure if thats possible to disable pokestop/gym gathering, map generation - may be it could help.

@drewreece so far pogom is the fastest way to gather data for later anaysis

**Comment by nborrmann** [comment]
@drewreece Please stop the FUD, you don't know what you're talking about. More accounts actually makes it less likely to get banned, because there is more time between requests from each account. @eXeLe is definitely bottlenecked by parsing and/or DB.

**Comment by eXeLe** [comment]
I changed for MariaDB and it looks like it works 3 times faster (~50% in 10min comparing to full scan with sqlite in 1hr), but I'm unable to make full scan because of softbans.

**Comment by drewreece** [comment]
I'm willing to admit I was wrong about the DB, apologies eXeLe. nborrmann are you willing to admit that soft bans are not FUD when mass scanning?

eXeLe, you may want to look at your DB & see if you can output a list of spawn points & times. There is a modification to PokemonGo-Map that is scanning spawns when they are known to be active. 
https://www.reddit.com/r/pokemongodev/comments/4wxteh/i_implemented_tbterras_spawntracker_into/?sort=new
Or try the project that originated the idea,
https://github.com/TBTerra/spawnScan

Since spawns run on a schedule it should be more efficient to scan at the right time instead of carpeting an area with requests, your DB should have that info now or maybe I just don't know what I'm talking about.

**Comment by compuguy** [comment]
@eXeLe I'm interested in getting MariaDB support, because the current sqlite implementation isn't great with a decent number of accounts.

**Comment by nborrmann** [comment]
#15
