### ISSUE TITLE
PTC Login Format of example VERY UNCLEAR 

### ISSUE THREAD

**Issue by Antitankers** [favll/pogom#236]
## Checklist
 - [X] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [X] I have checked if this issue already exists (both open and closed issues)
 - [X] I am using the most recent version of pogom from the master branch
 - [-] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [-] I'm posting the complete log
 - [X] I'm using a descriptive title for this issue

## My Issue
There is no clear indication of the formatting for more than one PTC account details in the config window
adding one using "username":"password" works perfectly but as the example suggests following that with no spaces and adding "username2":password2" doesn't do anything therefore I assume there must be some form of spacer to seperate the username and password 1 from the username and password 2 but it is not shown in the example !

...

**Comment by nborrmann** [comment]
There should be a linebreak in the hint, but it gets messed up in some browsers.

**Comment by herculys** [comment]
im using
```
name:pass
name2:pass2
name3:pass3
```

**Comment by teamcoltra** [comment]
I figured it was a line break because that's just how these usually work... but I agree that in webkit browsers it doesn't show a line break and it is confusing without text actually explaining that each line should be a new user. 

I would suggest this be moved from "enhancement" to "bug" as it currently does not function as expected and can confuse users.
