### ISSUE TITLE
How to disable the ability to change location from browser?

### ISSUE THREAD

**Issue by nvhk** [favll/pogom#46]
How to disable the ability to change location from browser?

**Comment by MarkusFlorian** [comment]
If you want to do it in your fork / copy of the code find the app.py file in the pogom folder, go to line 71, the definition of the set_location function and add a line with "abort(400)"

Stop reading here if you're lazy ;)

there is no parameter yet but can be easily included as well. 

In the utils.py file you can modify the get_args function and include a parameter of your choice  by copying one of the existing lines and modifying it. 

then in the runserver.py request the value of the new arguments and add it to the search config
i did it by passing the argument to the set_location function in the search.py file

now instead of writing abort(400) in the first line after the definition of set_location you could add
if SearchConfig.allowManualLocationChange:
   abort(400)

inseatd (or how you called your searchconfig parameter ;)

**Comment by favll** [comment]
Now possible with the new Pogom version.

**Comment by RvV1979** [comment]
Could you please explain how this is "now possible": is it now an simpler setting? How to set it when running the server? (The answer by MarkusFlorian is well above my paygrade... )
thanks
