### ISSUE TITLE
Load locale 

### ISSUE THREAD

**Issue by kalimerre** [favll/pogom#99]
Hello,

I want to load french locale on your tool but someone can tell me if there is an extra_arg to add to runserver.py ? 

Regards,

**Comment by lax20attack** [comment]
In \static\map.js

Change this:
`$.getJSON("static/locales/pokemon.en.json").done(function(data) {`


To this:

`$.getJSON("static/locales/pokemon.fr.json").done(function(data) {`

**Comment by NatsuOnFire** [comment]
Pokemon label is always in english with this config

**Comment by sheridan-dev** [comment]
instead of changing the source code, just change the language setting in the file
> `pogom/__init__.py`

Before:
`'LOCALE': 'en',`

After:
`'LOCALE': 'fr'`

But remember that this change will be overwritten when pulling a new version from the git repository.

The file `static/map.js` is not responsible for the map labels.

**Comment by favll** [comment]
We should move LOCALE to config.json
